name: CI

on:
  workflow_dispatch:
    inputs:
      iterations:
        default: '20000'

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Nodejs 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- test/integration/eperm.ts
        env:
          RIMRAF_TEST_EPERM_ITERATIONS: ${{ inputs.iterations }}
